coverage:
  ignore: 
    - "tests"
  status:
    project:  # Measures overall project coverage.
      default: false
      gui:
        target: auto
        threshold: 0.5%  # Some leeway with GUI code.
        paths:
          - "sleap/gui/"
      non-gui:
        target: auto
        threshold: 0.05%  # Less leeway with backend code.
        paths:
          - "sleap/"
          - "!sleap/gui/"
    patch:  #  Only measures lines adjusted in the pull request.
      default: false
      gui:
        target: auto
        paths:
          - "sleap/gui/"
        informational: true  # GUI patch coverage for stats only.
      non-gui:
        target: 100%  # All backend code should be tested...
        threshold: 20%  # ... but some tests are infeasable.
        paths:
          - "sleap/"
          - "!sleap/gui/"
