coverage:
  status:
    project:
      default: false
      gui:
        target: auto
        threshold: 0.03%
        paths: 
          - "sleap/gui/"
      backend:
        target: auto
        threshold: 0%
        paths: 
          - "!sleap/gui/"
