# We specify the numpy version here for build compatibility.
# 
# Ref: https://docs.conda.io/projects/conda-build/en/latest/resources/variants.html#conda-build-variant-config-files

python:
  - 3.7

numpy:
  - 1.19.5
  # - 1.21.2