# Ref: https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html

# Jinja template: Process setup.py to obtain version and metadata
{% set data = load_setup_py_data() %}


package:
  # Repeating name because of the following issue:
  # https://github.com/conda/conda-build/issues/2475
  name: sleap
  version: {{ data.get('version') }}

about:
  home: {{ data.get('url') }}
  license: {{ data.get('license') }}
  summary: {{ data.get('description') }}

build:
  # number: {{ GIT_DESCRIBE_NUMBER }}
  number: {{ data.get('version') }}

source:
  path: ../

requirements:
  host:
    - python=3.7
    - sleap::tensorflow=2.7.0
    - sleap::pyside2=5.15.2
    - pip

  run:
    - python=3.7
    - cudatoolkit=11.3.1
    - cudnn=8.2.1
    - sleap::tensorflow=2.7.0
    - sleap::pyside2=5.15.2
    - Pillow
    - Shapely
    - pip

  run_constrained:
    - pyqt==9999999999

test:
  imports:
    - sleap