{% set data = load_setup_py_data() %}


package:
  # Repeating name because of the following issue:
  # https://github.com/conda/conda-build/issues/2475
  name: sleap
  version: {{ data.get('version') }}

about:
  home: {{ data.get('url') }}
  license: {{ data.get('license') }}
  summary: {{ data.get('description') }}

source:
  path: ../

build:
  number: 0

requirements:
  host:
    # - conda-forge::python ==3.7.12  # Run into _MAX_WINDOWS_WORKERS not found if <
    # - conda-forge::python >=3.9.0,<3.10.0
    - conda-forge::python >=3.10.0,<3.11.0
    # - numpy >=1.19.5,<1.23.0  # Linux likes anaconda, windows likes conda-forge
    - numpy >=1.21.6 # SciPy 1.11 requires numpy >=1.21.6
    - conda-forge::cudatoolkit ==11.3.1
    - conda-forge::cudnn=8.2.1
    - nvidia::cuda-nvcc=11.3
    - conda-forge::setuptools
    - conda-forge::pip

    # Only the packages above are required to build, but listing them all ensures no 
    # unnecessary pypi packages are installed via the build script (bld.bat, build.sh)
    - conda-forge::attrs ==21.4.0
    - conda-forge::cattrs ==1.1.1
    - conda-forge::h5py ==3.7.0
    - conda-forge::jsmin
    - conda-forge::jsonpickle ==1.2
    - conda-forge::networkx
    - conda-forge::opencv <4.9.0
    - conda-forge::pandas
    - conda-forge::pillow >=8.3.2
    - conda-forge::psutil
    - conda-forge::pykalman
    # - conda-forge::pyside2 >=5.12,<5.14  # To ensure works correctly with QtPy.
    # - conda-forge::pyside6 >5.15 # >5.15 is compatible with Python 3.9
    - conda-forge::pyside6 >=6.2.0 # >=6.2.0 is compatible with Python 3.10
    - conda-forge::python-rapidjson
    - conda-forge::pyyaml
    - conda-forge::pyzmq
    - conda-forge::qtpy >=2.0.1
    - conda-forge::rich
    # - conda-forge::scipy >=1.4.1,<=1.9.0
    - conda-forge::scipy >=1.11 # Python 3.9, 3.10 requires scipy >=1.11
    - conda-forge::scikit-image
    - conda-forge::scikit-learn ==1.0
    - conda-forge::scikit-video
    - conda-forge::seaborn
    - conda-forge::qudida
    - conda-forge::albumentations
    - conda-forge::ndx-pose
    - conda-forge::importlib-metadata ==4.11.4
  run:
    # - conda-forge::python ==3.7.12  # Run into _MAX_WINDOWS_WORKERS not found if <
    # - conda-forge::python >=3.9.0,<3.10.0
    - conda-forge::python >=3.10.0,<3.11.0
    # - numpy >=1.19.5,<1.23.0  # Linux likes anaconda, windows likes conda-forge
    - numpy >=1.21.6 # SciPy 1.11 requires numpy >=1.21.6
    - conda-forge::attrs ==21.4.0
    - conda-forge::cattrs ==1.1.1
    - conda-forge::cudatoolkit ==11.3.1
    - conda-forge::cudnn=8.2.1
    - nvidia::cuda-nvcc=11.3
    - conda-forge::h5py ==3.7.0
    - conda-forge::jsmin
    - conda-forge::jsonpickle ==1.2
    - conda-forge::networkx
    - conda-forge::opencv <4.9.0
    - conda-forge::pandas
    - conda-forge::pillow >=8.3.2
    - conda-forge::psutil
    - conda-forge::pykalman
    # - conda-forge::pyside2 >=5.12,<5.14  # To ensure works correctly with QtPy.
    # - conda-forge::pyside6 >5.15 # >5.15 is compatible with Python 3.9
    - conda-forge::pyside6 >=6.2.0 # >=6.2.0 is compatible with Python 3.10
    - conda-forge::python-rapidjson
    - conda-forge::pyyaml
    - conda-forge::pyzmq
    - conda-forge::qtpy >=2.0.1
    - conda-forge::rich
    # - conda-forge::scipy >=1.4.1,<=1.9.0
    - conda-forge::scipy >=1.11 # Python 3.9, 3.10 requires scipy >=1.11
    - conda-forge::scikit-image
    - conda-forge::scikit-learn ==1.0
    - conda-forge::scikit-video
    - conda-forge::seaborn
    - sleap/label/dev::tensorflow ==2.7.0  # TODO: Switch to main label when updated
    - conda-forge::tensorflow-hub <0.14.0  # Causes pynwb conflicts on linux GH-1446
    - conda-forge::qudida
    - conda-forge::albumentations
    - conda-forge::ndx-pose
    - conda-forge::importlib-metadata ==4.11.4

# This no longer works so we have moved it to the build workflow
# https://github.com/talmolab/sleap/pull/1744
# test:
#   imports:
#     - sleap