# Ref: https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html

# Jinja template: Process setup.py to obtain version and metadata
{% set data = load_setup_py_data() %}


package:
  # Repeating name because of the following issue:
  # https://github.com/conda/conda-build/issues/2475
  name: sleap
  version: {{ data.get('version') }}

about:
  home: {{ data.get('url') }}
  license: {{ data.get('license') }}
  summary: {{ data.get('description') }}

build:
  number: 1

source:
  path: ../

requirements:
  host:
    - python=3.7
    # - sleap::pyside2=5.14.1
    - conda-forge::numpy=1.21.5
    - sleap::tensorflow=2.7.0
    - conda-forge::pyside2=5.13.2
    - conda-forge::h5py=3.6.0
    - conda-forge::scipy=1.7.3
    - pillow=8.4.0
    - shapely=1.7.1
    - conda-forge::pandas
    - ffmpeg
    - pip

  run:
    - python=3.7
    - conda-forge::numpy>=1.19.5,<=1.21.5
    - sleap::tensorflow>=2.6.3,<=2.7.1
    - conda-forge::pyside2>=5.13.2,<=5.14.1
    - conda-forge::h5py>=3.1.0,<=3.6.0
    - conda-forge::scipy>=1.4.1,<=1.7.3
    - pillow=8.4.0
    - shapely=1.7.1
    - conda-forge::pandas
    - ffmpeg
    - cudatoolkit=11.3.1
    - cudnn=8.2.1
    - nvidia::cuda-nvcc=11.3
    - pip

  run_constrained:
    - pyqt==9999999999

test:
  imports:
    - sleap