{% set data = load_setup_py_data() %}


package:
  # Repeating name because of the following issue:
  # https://github.com/conda/conda-build/issues/2475
  name: sleap
  version: {{ data.get('version') }}

about:
  home: {{ data.get('url') }}
  license: {{ data.get('license') }}
  summary: {{ data.get('description') }}

source:
  path: ../

build:
  number: 3

requirements:
  host:
    - conda-forge::python ==3.7
    - anaconda::numpy >=1.19.5,<1.23.0
    - conda-forge::cudatoolkit ==11.3.1
    - conda-forge::cudnn=8.2.1
    - nvidia::cuda-nvcc=11.3
    - conda-forge::setuptools
    - conda-forge::packaging
    - conda-forge::pip

    # Only the packages above are required to build, but listing them all ensures no 
    # unnecessary pypi packages are installed via the build script (bld.bat, build.sh)
    - conda-forge::attrs ==21.4.0
    - conda-forge::cattrs ==1.1.1
    - conda-forge::h5py ==3.1  # [not win]
    - conda-forge::imgaug ==0.4.0
    - conda-forge::jsmin
    - conda-forge::jsonpickle ==1.2
    - conda-forge::networkx
    - conda-forge::opencv
    - conda-forge::pandas
    - conda-forge::pillow >=8.3.2
    - conda-forge::psutil
    - conda-forge::pykalman
    - conda-forge::pyside2 >=5.12,<5.14
    - conda-forge::python-rapidjson
    - conda-forge::pyyaml
    - conda-forge::pyzmq
    - conda-forge::qtpy >=2.0.1
    - conda-forge::rich
    - conda-forge::scipy >=1.4.1,<=1.9.0
    - conda-forge::scikit-image
    - conda-forge::scikit-learn ==1.0
    - conda-forge::scikit-video
    - conda-forge::seaborn
  run:
    - conda-forge::python ==3.7
    - conda-forge::attrs ==21.4.0
    - conda-forge::cattrs ==1.1.1
    - conda-forge::cudatoolkit ==11.3.1
    - conda-forge::cudnn=8.2.1
    - nvidia::cuda-nvcc=11.3
    - conda-forge::h5py ==3.1  # [not win]
    - conda-forge::imgaug ==0.4.0
    - conda-forge::jsmin
    - conda-forge::jsonpickle ==1.2
    - conda-forge::networkx
    - anaconda::numpy >=1.19.5,<1.23.0
    - conda-forge::opencv
    - conda-forge::pandas
    - conda-forge::pillow >=8.3.2
    - conda-forge::psutil
    - conda-forge::pykalman
    - conda-forge::pyside2 >=5.12,<5.14  # To ensure works correctly with QtPy.
    - conda-forge::python-rapidjson
    - conda-forge::pyyaml
    - conda-forge::pyzmq
    - conda-forge::qtpy >=2.0.1
    - conda-forge::rich
    - conda-forge::scipy >=1.4.1,<=1.9.0
    - conda-forge::scikit-image
    - conda-forge::scikit-learn ==1.0
    - conda-forge::scikit-video
    - conda-forge::seaborn
    - sleap::tensorflow >=2.6.3,<2.11  # No windows GPU support for >2.10, sleap channel has 2.6.3
    - conda-forge::tensorflow-hub

test:
  imports:
    - sleap