{% set data = load_setup_py_data() %}


package:
  # Repeating name because of the following issue:
  # https://github.com/conda/conda-build/issues/2475
  name: sleap
  version: {{ data.get('version') }}

about:
  home: {{ data.get('url') }}
  license: {{ data.get('license') }}
  summary: {{ data.get('description') }}

source:
  path: ../

build:
  number: 0

requirements:
  host:
    - conda-forge::python >=3.10.0,<3.11.0
    - numpy >=1.16.5,<2.0 # SciPy 1.7 requires numpy >=1.16.5
    - conda-forge::cudatoolkit ==11.3.1
    - conda-forge::cudnn=8.2.1
    - nvidia::cuda-nvcc=11.3
    - conda-forge::setuptools
    - conda-forge::pip

    # Only the packages above are required to build, but listing them all ensures no 
    # unnecessary pypi packages are installed via the build script (bld.bat, build.sh)
    - conda-forge::attrs
    - conda-forge::cattrs
    - conda-forge::h5py
    - conda-forge::imageio
    - conda-forge::imageio-ffmpeg
    - conda-forge::jsmin
    - conda-forge::jsonpickle <=1.5.0 # 1.5.1 breaks compatibility with v1 encoded files
    - conda-forge::networkx
    - conda-forge::opencv
    - conda-forge::pandas
    - conda-forge::pillow
    - conda-forge::psutil
    - conda-forge::pykalman
    - conda-forge::pyside6 >=6.5.0 # 6.4 conda package uses problematic QtCharts
    - conda-forge::python-rapidjson
    - conda-forge::pyyaml
    - conda-forge::pyzmq
    - conda-forge::qtpy >=2.0.1
    - conda-forge::rich
    - conda-forge::scipy >=1.7.0 # Python 3.10 requires scipy >=1.7
    - conda-forge::scikit-image
    - conda-forge::scikit-learn >=1.0.0 # Python 3.10 requires scikit-learn >=1.0
    - conda-forge::seaborn
    - sleap-deps/label/dev::tensorflow ==2.9.2a0 # TODO: Switch to main label when updated
    - conda-forge::tensorflow-hub
    - conda-forge::qudida
    - conda-forge::albumentations
    - conda-forge::ndx-pose
    - conda-forge::importlib-metadata
  run:
    - conda-forge::python >=3.10.0,<3.11.0
    - numpy >=1.16.5,<2.0 # SciPy 1.7 requires numpy >=1.16.5
    - conda-forge::attrs
    - conda-forge::cattrs
    - conda-forge::cudatoolkit ==11.3.1
    - conda-forge::cudnn=8.2.1
    - nvidia::cuda-nvcc=11.3
    - conda-forge::h5py
    - conda-forge::imageio
    - conda-forge::imageio-ffmpeg
    - conda-forge::jsmin
    - conda-forge::jsonpickle <=1.5.0 # 1.5.1 breaks compatibility with v1 encoded files
    - conda-forge::networkx
    - conda-forge::opencv
    - conda-forge::pandas
    - conda-forge::pillow
    - conda-forge::psutil
    - conda-forge::pykalman
    - conda-forge::pyside6 >=6.5.0 # 6.4 conda package uses problematic QtCharts
    - conda-forge::python-rapidjson
    - conda-forge::pyyaml
    - conda-forge::pyzmq
    - conda-forge::qtpy >=2.0.1
    - conda-forge::rich
    - conda-forge::scipy >=1.7.0 # Python 3.10 requires scipy >=1.7
    - conda-forge::scikit-image
    - conda-forge::scikit-learn >=1.0.0 # Python 3.10 requires scikit-learn >=1.0
    - conda-forge::seaborn
    - sleap-deps/label/dev::tensorflow ==2.9.2a0 # TODO: Switch to main label when updated
    - conda-forge::tensorflow-hub
    - conda-forge::qudida
    - conda-forge::albumentations
    - conda-forge::ndx-pose
    - conda-forge::importlib-metadata

test:
  requires:
    - pip
    - libopencv *=headless*  # [linux] https://github.com/conda-forge/opencv-feedstock/issues/401#issuecomment-2028099423
# This no longer works so we have moved it to the build workflow
# https://github.com/talmolab/sleap/pull/1744
#   imports:
#     - sleap
