# Setup a list of packages that aren't conda installable
{% set conda_skip = (
    "cattrs",
    "opencv-python",
    "PySide2",
    "imgaug"
) %}

{% set data = load_setup_py_data() %}

source:
  path: ../

package:
  # Repeating name because of the following issue:
  # https://github.com/conda/conda-build/issues/2475
  name: sleap
  version: 0.1.0

about:
  home: {{ data.get('url') }}
  license: {{ data.get('license') }}
  summary: {{ data.get('description') }}

build:
  number: 0

source:
  path: ../

requirements:
  host:
    - python=3.6
    - attrs
    - jsonpickle
    - networkx
    - tensorflow-gpu
    - keras
    - scikit-learn
    - h5py
    - pandas
    - Shapely
    - psutil
    - pyzmq


  run:
    - python=3.6
    - attrs
    - jsonpickle
    - networkx
    - tensorflow-gpu
    - keras
    - scikit-learn
    - h5py
    - pandas
    - Shapely
    - psutil
    - pyzmq

