# Ref: https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html

# Jinja template: Process setup.py to obtain version and metadata
{% set data = load_setup_py_data() %}


package:
  # Repeating name because of the following issue:
  # https://github.com/conda/conda-build/issues/2475
  name: sleap
  version: {{ data.get('version') }}

about:
  home: {{ data.get('url') }}
  license: {{ data.get('license') }}
  summary: {{ data.get('description') }}

build:
  number: 0

source:
  path: ../

requirements:
  host:  
    - conda-forge::python >=3.10.0,<3.11.0
    - conda-forge::numpy >=1.16.5 # Scipy 1.7.0 requires numpy >=1.16.5
    - conda-forge::setuptools
    - conda-forge::packaging
    - conda-forge::pip

    # Only the packages above are required to build, but listing them all ensures no 
    # unnecessary pypi packages are installed via the build script (bld.bat, build.sh)
    - conda-forge::attrs >=21.2.0
    - conda-forge::cattrs
    - conda-forge::h5py
    - conda-forge::imageio
    - conda-forge::imageio-ffmpeg
    - conda-forge::jsmin
    - conda-forge::jsonpickle
    - conda-forge::networkx
    - conda-forge::opencv
    - conda-forge::pandas
    - conda-forge::pillow
    - conda-forge::psutil
    - conda-forge::pykalman
    - conda-forge::pyside6 >=6.5.0 # 6.4 conda package uses problematic QtCharts
    - conda-forge::python-rapidjson
    - conda-forge::pyyaml
    - conda-forge::pyzmq
    - conda-forge::qtpy >=2.0.1
    - conda-forge::rich
    - conda-forge::scipy >=1.7.0 # Python 3.10 needs scipy >= 1.7.0
    - conda-forge::scikit-image
    - conda-forge::scikit-learn >=1.0.0 # Python 3.10 needs scikit-learn >= 1.0
    - conda-forge::seaborn
    - sleap-deps/label/dev::tensorflow ==2.12.0 # TODO: Switch to main label when updated
    - conda-forge::qudida
    - conda-forge::albumentations
    - conda-forge::ndx-pose

  run:
    - conda-forge::python >=3.10.0,<3.11.0
    - conda-forge::attrs >=21.2.0
    - conda-forge::cattrs
    - conda-forge::h5py
    - conda-forge::imageio
    - conda-forge::imageio-ffmpeg
    - conda-forge::jsmin
    - conda-forge::jsonpickle
    - conda-forge::networkx
    - conda-forge::numpy >=1.16.5 # Scipy 1.7.0 requires numpy >=1.16.5
    - conda-forge::opencv
    - conda-forge::pandas
    - conda-forge::pillow
    - conda-forge::psutil
    - conda-forge::pykalman
    - conda-forge::pyside6 >=6.5.0 # 6.4 conda package uses problematic QtCharts
    - conda-forge::python-rapidjson
    - conda-forge::pyyaml
    - conda-forge::pyzmq
    - conda-forge::qtpy >=2.0.1
    - conda-forge::rich
    - conda-forge::scipy >=1.7.0 # Python 3.10 is compatible with scipy >=1.7.0
    - conda-forge::scikit-image
    - conda-forge::scikit-learn >=1.0.0 # Python 3.10 needs scikit-learn >= 1.0
    - conda-forge::seaborn
    - sleap-deps/label/dev::tensorflow ==2.9.2a0 # TODO: Switch to main label when updated
    - conda-forge::qudida
    - conda-forge::albumentations
    - conda-forge::ndx-pose
