main:

  - name: min_frame_idx
    label: Minimum frame index
    type: int
    range: 1,1000000
    default: 1

  - name: max_frame_idx
    label: Maximum frame index
    type: int
    range: 1,1000000
    default: 1000