name: Comment on New Discussions

on:
  discussion:
    types: [created]

jobs:
  comment:
    runs-on: ubuntu-latest

    steps:
      - name: Post a comment on a new discussion
        uses: actions/github-script@v6
        with:
          script: |
            const { owner, repo } = context.repo;
            const discussion_id = context.payload.discussion.node_id;

            const mutation = `
              mutation($discussionId: ID!, $body: String!) {
                addDiscussionComment(input: {discussionId: $discussionId, body: $body}) {
                  comment {
                    id
                  }
                }
              }
            `;

            await github.graphql(mutation, {
              discussionId: discussion_id,
              body: ':warning: Thank you for starting a new discussion! We will get back to you soon.'
            });
