# Docs build
name: Docs

on:
  workflow_dispatch
#   release:
#     types:
#       - published
#   push:
#     branches:
#       - main
#       - develop
#     paths:
#       - "sleap/**"
#       - "docs/**"
#       - "mkdocs.yml"
#       - ".github/workflows/docs.yml"

jobs:
  docs:
    name: Docs
    runs-on: "ubuntu-latest"
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for all branches

      - name: Setup UV
        uses: astral-sh/setup-uv@v6
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          uv sync --all-extras

      - name: Print environment info
        run: |
          uv run python --version
          uv run pip freeze

      - name: Setup Git user
        run: |
            git config --global user.name "github-actions[bot]"
            git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Build and upload docs (release)
        if: ${{ github.event_name == 'release' && github.event.action == 'published' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
            uv run mike deploy --update-aliases --allow-empty --push "${{ github.event.release.tag_name }}" latest

      - name: Build and upload docs (dev)
        if: ${{ github.event_name == 'push' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
            uv run mike deploy --update-aliases --allow-empty --push dev